spring.application.name=query-api

# REST API'nin dinleyecegi port (tarayicidan http://localhost:8080)
server.port=8080

# --- AWS / LocalStack ---
aws.region=eu-central-1
aws.endpoint=http://localhost:4566
aws.access-key=test
aws.secret-key=test

# --- Kaynak ismi ---
app.dynamodb.table-name=telemetry
